default:
  app_name: "course-planner"
  functions_url: "https://us-central1-polish-canopy.cloudfunctions.net/signInWithToken"
  db:
    dbname: "course-planner-dev"
    host: "104.196.200.157"
    port: 5432
    user: "postgres"
    password: "attic_12_escape"

production:
  tychobra_origin: "https://canopy.tychobra.com"
functions_url: "https://us-central1-polish-canopy.cloudfunctions.net/signInWithToken"
app_name: "course-planner"
db:
  dbname: "course-planner-prod"
  host: "104.196.200.157"
  port: 5432
  user: "postgres"
  password: "attic_12_escape"
